controller_manager:
  ros__parameters:
    update_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel_names: ["left_wheel"]
  right_wheel_names: ["right_wheel"]
  publish_rate: 50.0
  base_frame_id: base_link
  odom_frame_id: odom
  wheel_separation: 0.324
  wheel_radius: 0.05
  use_stamped_vel: false
  enable_odom_tf: true